server:
  port: 8770

spring:
  application:
    name: file-service
  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/financial_saas
    username: heyake
    password: EnablingSoft@2025
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: financial-saas
