server:
  port: 9200

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: tenant-service
          uri: http://localhost:8080
          predicates:
            - Path=/tenants/**
        - id: user-service
          uri: http://localhost:8762
          predicates:
            - Path=/users/**
        - id: org-service
          uri: http://localhost:8763
          predicates:
            - Path=/orgs/**
        - id: trans-service
          uri: http://localhost:8764
          predicates:
            - Path=/trans/**
        - id: loan-service
          uri: http://localhost:8765
          predicates:
            - Path=/loans/**
        - id: repayment-service
          uri: http://localhost:8766
          predicates:
            - Path=/repayments/**
        - id: approval-service
          uri: http://localhost:8767
          predicates:
            - Path=/approvals/**
        - id: notification-service
          uri: http://localhost:8768
          predicates:
            - Path=/notification/**
        - id: report-service
          uri: http://localhost:8769
          predicates:
            - Path=/report/**
        - id: file-service
          uri: http://localhost:8770
          predicates:
            - Path=/file/**
