server:
  port: 8769

spring:
  application:
    name: report-service
  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/financial_saas
    username: heyake
    password: EnablingSoft@2025
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
